"""knowledge base tables

Revision ID: 0837eff58b0e
Revises: 
Create Date: 2026-10-03 00:43:21.051443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0837eff58b0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('legal_level', sa.String(length=20), nullable=False),
    sa.Column('authority', sa.Text(), nullable=False),
    sa.Column('issuing_instrument', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('collected_on', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('legal_provisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('article_number', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title_ar', sa.Text(), nullable=False),
    sa.Column('hierarchy', sa.Text(), nullable=True),
    sa.Column('text_ar', sa.Text(), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('related_record_ids', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_note', sa.Text(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['legal_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_index(op.f('ix_legal_provisions_article_number'), 'legal_provisions', ['article_number'], unique=False)
    op.create_index(op.f('ix_legal_provisions_source_id'), 'legal_provisions', ['source_id'], unique=False)
    op.create_table('provision_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provision_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('retrieval_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['provision_id'], ['legal_provisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provision_id', 'chunk_index')
    )
    op.create_index(op.f('ix_provision_chunks_provision_id'), 'provision_chunks', ['provision_id'], unique=False)
    # ### end Alembic commands ###
    # Approximate nearest-neighbour index for semantic search (cosine distance).
    op.execute(
        "CREATE INDEX ix_provision_chunks_embedding ON provision_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_provision_chunks_embedding")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provision_chunks_provision_id'), table_name='provision_chunks')
    op.drop_table('provision_chunks')
    op.drop_index(op.f('ix_legal_provisions_source_id'), table_name='legal_provisions')
    op.drop_index(op.f('ix_legal_provisions_article_number'), table_name='legal_provisions')
    op.drop_table('legal_provisions')
    op.drop_table('legal_sources')
    # ### end Alembic commands ###
