"""users, owned cases, documents, claims

Revision ID: d53eaa2f88a4
Revises: 666b56dfd6c7
Create Date: 2026-10-08 02:33:17.520561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd53eaa2f88a4'
down_revision: Union[str, Sequence[str], None] = '666b56dfd6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('case_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('party_vault', sa.Text(), nullable=True),
    sa.Column('grounding_warnings', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_claims_case_id'), 'case_claims', ['case_id'], unique=False)
    op.create_table('case_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('masked_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_documents_case_id'), 'case_documents', ['case_id'], unique=False)
    op.add_column('cases', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('cases', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('employee_gender', sa.String(length=6), nullable=True))
    op.add_column('cases', sa.Column('pii_vault', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_cases_user_id'), 'cases', ['user_id'], unique=False)
    op.create_foreign_key(None, 'cases', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_index(op.f('ix_cases_user_id'), table_name='cases')
    op.drop_column('cases', 'updated_at')
    op.drop_column('cases', 'pii_vault')
    op.drop_column('cases', 'employee_gender')
    op.drop_column('cases', 'title')
    op.drop_column('cases', 'user_id')
    op.drop_index(op.f('ix_case_documents_case_id'), table_name='case_documents')
    op.drop_table('case_documents')
    op.drop_index(op.f('ix_case_claims_case_id'), table_name='case_claims')
    op.drop_table('case_claims')
    op.drop_table('users')
    # ### end Alembic commands ###
