// All interface wording in one place, so copy can be edited without touching components.

export const text = {
  appName: "قسطاس",
  tagline: "مساعد قانوني ذكي لقضايا نظام العمل السعودي",
  nav: {
    analyze: "تحليل قضية",
    search: "البحث في النظام",
    myCases: "قضاياي",
    admin: "إدارة المستخدمين",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    logout: "تسجيل الخروج",
  },

  form: {
    title: "صف حالتك العمالية",
    descriptionLabel: "وصف الحالة",
    descriptionHint: "اذكر ما حدث، ومدة خدمتك، ونوع العقد، والأجر، وما تريد معرفته. كلما زادت التفاصيل كان التحليل أدق.",
    descriptionPlaceholder: "مثال: أعمل في شركة منذ 6 سنوات بعقد غير محدد المدة، وراتبي 8000 ريال، وتم فصلي بدون سبب ولا إشعار...",
    genderLabel: "جنس العامل",
    genderHint: "بعض الأحكام تختلف بحسب الجنس، ولا يمكن استنتاجه بعد إخفاء الاسم.",
    genderUnset: "غير محدد",
    male: "ذكر",
    female: "أنثى",
    employeeNameLabel: "اسم العامل (اختياري)",
    employerNameLabel: "اسم صاحب العمل أو المنشأة (اختياري)",
    privacyNote: "يُخفى الاسم ورقم الهوية والجوال والآيبان تلقائياً قبل إرسال الحالة للذكاء الاصطناعي، ولا تُحفظ البيانات الأصلية.",
    submit: "حلّل الحالة",
    submitting: "جارٍ التحليل…",
    waitNote: "قد يستغرق التحليل من 15 ثانية إلى دقيقة ونصف.",
    tooShort: "يرجى كتابة وصف لا يقل عن 30 حرفاً.",
  },

  result: {
    outcome: "النتيجة المتوقعة",
    likelihood: "درجة الترجيح",
    reasoning: "السبب",
    entitlements: "المستحقات المالية",
    entitlementsNote: "محسوبة آلياً وفق مواد النظام، وليست من تقدير الذكاء الاصطناعي.",
    total: "الإجمالي",
    cannotCompute: "لا يمكن الحساب لنقص معلومات",
    facts: "ملخص الوقائع",
    issues: "المسائل القانونية",
    analysis: "التحليل",
    missing: "معلومات تحتاج لتوضيحها",
    steps: "الخطوات المقترحة",
    citations: "المواد النظامية المستند إليها",
    showText: "عرض نص المادة",
    hideText: "إخفاء النص",
    privacy: "ما الذي أُرسل للذكاء الاصطناعي؟",
    maskedCount: "بيانات شخصية تم إخفاؤها",
    kbAsOf: "قاعدة المعرفة محدّثة حتى",
    newCase: "تحليل حالة جديدة",
    warnings: "تنبيهات",
  },

  search: {
    title: "البحث في نظام العمل ولائحته التنفيذية",
    placeholder: "اكتب سؤالاً أو موضوعاً، مثل: إجازة الحج، أو المادة 84",
    submit: "بحث",
    empty: "لا توجد نتائج.",
  },

  article: { back: "رجوع", repealed: "ملغاة", merged: "مدمجة في مادة أخرى", source: "المصدر" },

  status: { repealed: "ملغاة", merged: "مدمجة", in_force: "سارية" } as Record<string, string>,

  // ----- demo pages (accounts, my cases, claim, upload, admin) -----
  auth: {
    loginTitle: "تسجيل الدخول",
    registerTitle: "إنشاء حساب جديد",
    identifier: "اسم المستخدم أو البريد الإلكتروني",
    username: "اسم المستخدم",
    usernameHint: "3–32 حرفاً إنجليزياً أو أرقاماً أو . _ -",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    passwordHint: "8 أحرف على الأقل",
    loginButton: "دخول",
    registerButton: "إنشاء الحساب",
    noAccount: "ليس لديك حساب؟",
    haveAccount: "لديك حساب؟",
    sessionNote: "تنتهي الجلسة تلقائياً بعد 30 دقيقة من عدم النشاط.",
    loading: "جارٍ التحقق من تسجيل الدخول…",
    forbidden: "هذه الصفحة متاحة للمشرف فقط.",
  },
  upload: {
    title: "مستندات داعمة (اختياري)",
    hint: "PDF أو صورة (JPG / PNG / WEBP)، حتى 10 ميجابايت و10 صفحات، وحتى 3 مستندات.",
    choose: "اختر ملفاً",
    extract: "استخراج النص",
    extracting: "جارٍ القراءة…",
    consent:
      "أوافق على إرسال الصور والمستندات الممسوحة ضوئياً إلى خدمة Gemini من Google لقراءتها. (ملفات PDF النصية تُقرأ على الخادم ولا تُرسل.)",
    consentNeeded: "هذا الملف صورة أو مسح ضوئي ويحتاج موافقتك أعلاه لقراءته.",
    review: "راجع النص المستخرج وصحّحه إن لزم قبل التحليل:",
    textLayer: "نص PDF (قُرئ على الخادم)",
    ocr: "قراءة آلية (Gemini)",
    garbled: "النص يبدو مشوّهاً؟ أعد القراءة بـ Gemini",
    remove: "إزالة",
    max: "الحد الأقصى 3 مستندات.",
  },
  cases: {
    title: "قضاياي",
    empty: "لا توجد قضايا بعد.",
    newCase: "تحليل قضية جديدة",
    version: "إصدار التحليل",
    total: "إجمالي المستحقات",
    hasClaim: "مسودة دعوى",
    updated: "آخر تحديث",
    open: "فتح",
  },
  caseDetail: {
    back: "→ قضاياي",
    rename: "تعديل العنوان",
    save: "حفظ",
    cancel: "إلغاء",
    downloadReport: "تنزيل التقرير PDF",
    edit: "تعديل الوصف وإعادة التحليل",
    reanalyze: "إعادة التحليل",
    reanalyzing: "جارٍ إعادة التحليل…",
    delete: "حذف القضية",
    confirmDelete: "هل تريد حذف هذه القضية نهائياً؟ لا يمكن التراجع.",
    documents: "المستندات المرفقة",
  },
  claim: {
    title: "مسودة صحيفة الدعوى",
    intro: "تُنشأ المسودة من التحليل. بيانات الأطراف أدناه لا تُرسل للذكاء الاصطناعي، وتُضاف للمسودة مباشرة.",
    nationalId: "رقم هوية / إقامة المدعي",
    nationality: "جنسية المدعي",
    phone: "جوال المدعي",
    address: "عنوان المدعي",
    crNumber: "السجل التجاري / الرقم الموحد للمنشأة",
    defendantAddress: "عنوان المنشأة",
    courtCity: "مدينة المحكمة العمالية",
    generate: "إنشاء مسودة صحيفة الدعوى",
    regenerate: "إنشاء مسودة جديدة",
    generating: "جارٍ إعداد المسودة…",
    plaintiff: "المدعي",
    defendant: "المدعى عليه",
    subject: "موضوع الدعوى",
    facts: "الوقائع",
    grounds: "الأسانيد النظامية",
    requests: "الطلبات",
    total: "إجمالي المطالبات",
    notes: "ملاحظات",
    downloadPdf: "تنزيل PDF",
    downloadWord: "تنزيل Word (قابل للتعديل)",
    blank: "……",
  },
  admin: {
    title: "إدارة المستخدمين",
    username: "المستخدم",
    email: "البريد",
    role: "الدور",
    status: "الحالة",
    cases: "القضايا",
    lastLogin: "آخر دخول",
    active: "نشط",
    inactive: "موقوف",
    activate: "تفعيل",
    deactivate: "إيقاف",
    roles: { user: "مستخدم", admin: "مشرف" } as Record<string, string>,
  },
} as const;
